# Run tests with Visual Studio 2017
image: Visual Studio 2017

environment:
  matrix:
    - CI_COMPILER: CLANG
    - CI_COMPILER: MSVC

install:
  # Install submodules
  - git submodule update --init

  # Get gnuplot
  - ps: Invoke-WebRequest https://fossies.org/windows/misc/gp524-win64-mingw_2.exe -OutFile gp.exe
  - start /wait gp.exe /VERYSILENT /SUPPRESSMSGBOXES
  - set PATH="C:\Program Files\gnuplot\bin";%PATH%

  - set PATH="C:\Program Files\LLVM\bin";%PATH%
  - clang-cl -v

  - dir "C:\Program Files\gnuplot"

build_script:
  - gradlew.bat build --stacktrace --console=plain -PwithBench

# Cache gradle downloads
cache:
  - C:\Users\appveyor\.gradle
